/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sia;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.regexp.joni.exception.ValueException;

/**
 *
 * @author Winsido
 */
public class CRUD1 extends javax.swing.JFrame {
SeConnecter c=new SeConnecter();

ResultSet rs;
Statement st;

    /**
     * Creates new form CRUD1
     */
    public CRUD1() {
        initComponents();
        this.setSize(450, 520);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        try {
            st=c.obtenirCon().createStatement();
            rs=st.executeQuery("select* from salle");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur Séléction","Erreur",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ti1 = new javax.swing.JTextField();
        ti2 = new javax.swing.JTextField();
        ti3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("capacité");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 290, 110, 50);

        jLabel2.setText("Num Salle ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 140, 110, 50);

        jLabel3.setText("Nomsalle");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 220, 110, 50);
        jPanel1.add(ti1);
        ti1.setBounds(100, 150, 240, 30);
        jPanel1.add(ti2);
        ti2.setBounds(100, 230, 240, 30);
        jPanel1.add(ti3);
        ti3.setBounds(100, 300, 240, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/edubase.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 0, 380, 140);

        b2.setBackground(new java.awt.Color(0, 94, 166));
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("AJOUTER");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(30, 390, 85, 30);

        b3.setBackground(new java.awt.Color(0, 94, 166));
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("MODIFIER");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(160, 390, 89, 30);

        b4.setBackground(new java.awt.Color(0, 94, 166));
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("SUPPRIMER");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(300, 390, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        
        try {
            
            int j=Integer.parseInt(ti1.getText());
            int d=Integer.parseInt(ti3.getText());
            salle s=new salle(j,ti2.getText(),d,true);
            
             st.executeUpdate("insert into salle(numsalle,nomsalle,capacité,dispo)values("+j+",'"+s.nomsalle+"',"+d+","+s.dispo+")");
             ti1.setText("");
             ti2.setText("");
             ti3.setText("");
             JOptionPane.showMessageDialog(null, "salle ajouté","information",JOptionPane.INFORMATION_MESSAGE);
             
        } catch (Exception e) {JOptionPane.showMessageDialog(null, "Erreur","Erruer",JOptionPane.ERROR_MESSAGE);
        }  
         
        
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
    try {
            int i=Integer.parseInt(ti1.getText());
            int d=Integer.parseInt(ti3.getText());
            st.executeUpdate("update salle set nomsalle='"+ti2.getText()+"' , capacité="+d+" where numsalle="+i);
            JOptionPane.showMessageDialog(null, "salle modifier","Information",JOptionPane.INFORMATION_MESSAGE);
            ti1.setText(""); ti2.setText(""); ti3.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e,"Erreur",JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
    if(JOptionPane.showConfirmDialog(null, "Ets vous sure","confirmer",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
        try {
            int i=Integer.parseInt(ti1.getText());
            
            
            st.executeUpdate("delete from salle  where numsalle="+i);
            JOptionPane.showMessageDialog(null, "salle supprimé","Information",JOptionPane.INFORMATION_MESSAGE);
            ti1.setText(""); ti2.setText(""); ti3.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Veillez Inserer le num de la salle a supprimer","Erreur",JOptionPane.ERROR_MESSAGE);
        } 
    }
    }//GEN-LAST:event_b4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ti1;
    private javax.swing.JTextField ti2;
    private javax.swing.JTextField ti3;
    // End of variables declaration//GEN-END:variables
}
