/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sia;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Winsido
 */
public class gererreservation extends javax.swing.JFrame {

    SeConnecter c = new SeConnecter();
    DefaultTableModel model = new DefaultTableModel();

    ResultSet rs, rs1, rs2;
    Statement st;
    String x = "";

    /**
     * Creates new form gererreservation
     */
    String n,p;
    int tt;
    public gererreservation(String n,String p , int tt) {
        initComponents();
        this.setSize(1450, 820);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        model.addColumn("id demande");
        model.addColumn("num salle ");
        model.addColumn("date Debut");
        model.addColumn("date Fin ");
        model.addColumn("nbr data show");
        model.addColumn("nbr pc  ");
        model.addColumn("date debut  ");
        model.addColumn("date fin");
        model.addColumn("id individu");
        model.addColumn("Email ");
        model.addColumn("Description");
        this.n=n;
        this.p=p;
        this.tt=tt;
        
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        System.out.println("" + sdf.format(d));

        try {
            String x = sdf.format(d);
            st = c.obtenirCon().createStatement();
            //st.executeUpdate("SELECT * FROM demande wehre demande.datedebs > '"+d+"' OR demande.datedebm > '"+d+"'  ORDER BY demande.iddem ");
            //  rs=st.executeQuery("SELECT * from demande WHERE demande.datedebs < '"+d+"' OR demande.datedebm < '"+d+"' ORDER BY demande.iddem");
            rs = st.executeQuery("SELECT * from demande WHERE(demande.datedebs > '" + x + "' OR demande.datedebm > '" + x + "') AND demande.etat=1 AND demande.iddem NOT IN (select reservation.iddem from reservation) ORDER BY demande.iddem");
            //id,numsalle,dd,df,nd,np,dd,df,id,em,dis
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur Séléction", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    }

    gererreservation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        t = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        tf = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 94, 166));
        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 220, 820);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/edubase.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(600, 20, 380, 110);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 400, 1010, 340);
        jPanel1.add(t1);
        t1.setBounds(320, 220, 150, 40);
        jPanel1.add(t2);
        t2.setBounds(490, 220, 150, 40);
        jPanel1.add(t3);
        t3.setBounds(660, 220, 150, 40);

        t.setColumns(20);
        t.setRows(5);
        jScrollPane2.setViewportView(t);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(830, 190, 410, 150);

        jButton1.setBackground(new java.awt.Color(0, 94, 166));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VALIDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1260, 200, 100, 70);
        jPanel1.add(tf);
        tf.setBounds(261, 226, 50, 40);

        jMenu1.setText("Log out");

        jMenuItem1.setText("Déconnexion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Quitté");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("page Menu");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        tf.setText(model.getValueAt(jTable1.getSelectedRow(), 0) + "");
        t1.setText(model.getValueAt(jTable1.getSelectedRow(), 1) + "");
        t2.setText(model.getValueAt(jTable1.getSelectedRow(), 4) + "");
        t3.setText(model.getValueAt(jTable1.getSelectedRow(), 5) + "");
        t.setText(model.getValueAt(jTable1.getSelectedRow(), 10) + "");

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //pbm de null dans la date remplacer par 1111-11-11
        // pbm de null dans le nb remplacer par le zero 
        try {
            //SALLE,PC,DATA SHOW , PC W DATASHOW f we9t wahed rahi temchi   temchi ghedwa nchlh ndir hal l materiel
            String dd1 = "", df1 = "", dd2 = "", df2 = "", email = "",cbp,mottt="";
            String ns = "", nd = "", np = "";
            int i = Integer.parseInt(tf.getText()), iddem = 0,mot=0;

            rs = st.executeQuery("select * from demande where demande.iddem=" + i);
            while (rs.next()) {
                dd1 = rs.getString(3);
                df1 = rs.getString(4);
                dd2 = rs.getString(7);
                df2 = rs.getString(8);
                email = rs.getString(10);
                ns = rs.getString(2);
                iddem = rs.getInt(9);
                mottt=rs.getString(11);

            }
             
             if(mottt.equals("soutenance")){
             mot=1;
             }
             if(mottt.equals("cours")){
             mot=2;
             }
             if(mottt.equals("recherche")){
             mot=3;
             }
            nd = t2.getText();
            np = t3.getText();
            System.out.println("" + dd1);
            System.out.println("" + dd2);
            //System.out.println("sia.gererreservation.jButton1ActionPerformed()"+dd1);
            if (t.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "ERROR","ERROR",JOptionPane.ERROR_MESSAGE);
            } else {
                if (!dd1.equals("1111-11-11")) {
                    if (dd2.equals("1111-11-11")) {
                        System.out.println(" if(!(dd1.equals(null)) )");
                        System.out.println("&& (dd2.equals(null" + dd2);
                        //reservation salle
                        System.out.println("je rentre ");
                        int dis = 1;
                        rs1 = st.executeQuery("SELECT dispo FROM salle where salle.numsalle=" + ns);
                        while (rs1.next()) {
                            dis = rs1.getInt(1);
                        }
                        if (dis == 1) {
                            //reservilou
                            int iddr = 0;// mot = 1;

                            st.executeUpdate("update salle set salle.dispo= 0 WHERE salle.numsalle=" + ns);

                            rs1 = st.executeQuery("select Max(idreservation) from reservation");
                            while (rs1.next()) {
                                iddr = rs1.getInt(1) + 1;
                            }
                            int mat = 0;
                            st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd1 + "' , '" + df1 + "' ," + mot + "," + ns + " , " + iddem + "," + i + "," + mat + ")");
                            System.out.println("ACCEPTED1" + iddr);
                            JOptionPane.showMessageDialog(null, "Demande Traiter","information",JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            //matresarvilouch
                            JOptionPane.showMessageDialog(null, "Demande Réfusé 1","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        int dis = 1;
                        rs1 = st.executeQuery("SELECT dispo FROM salle where salle.numsalle=" + ns);
                        while (rs1.next()) {
                            dis = rs1.getInt(1);
                        }
                        int iddr = 0, tp = 0, td = 0;// mot = 1;
                        if (!(np.equals("0"))) {
                            rs1 = st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1");
                            while (rs1.next()) {
                                tp = Integer.parseInt(rs1.getString(1));
                            }
                            rs2 = st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2");
                            while (rs2.next()) {
                                td = Integer.parseInt(rs2.getString(1));
                            }
                            System.out.println("pc11");
                            if (nd.equals("0")) {
                                if (Integer.parseInt(np) > tp) {
                                    System.out.println("pc22");
                                    //Réfuser
                                    JOptionPane.showMessageDialog(null, "Demande Réfusé 2","ERROR",JOptionPane.ERROR_MESSAGE);
                                } else {
                                    if (dis == 1) {
                                        //reservilou

                                        st.executeUpdate("update salle set salle.dispo= 0 WHERE salle.numsalle=" + ns);

                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                        }
                                        int mat = 0;
                                        st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd1 + "' , '" + df1 + "' ," + mot + "," + ns + " , " + iddem + "," + i + "," + mat + ")");
                                        System.out.println("ACCEPTED2" + iddr);
                                        System.out.println("pc33");
                                        //dirlou reserv
                                        int idmat = 0;
                                        rs1 = st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1 and dispo=1");
                                        while (rs1.next()) {
                                            idmat = rs1.getInt(1);
                                        }
                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                        }
                                        st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd2 + "' , '" + df2 + "' ," + mot + "," + null + " , " + iddem + "," + i + "," + idmat + ")");
                                        st.executeUpdate("update materiel set dispo = 0 where idmateriel=" + idmat);

                                        System.out.println("ACCEPTED 3");
                                        JOptionPane.showMessageDialog(null, "Demande Traiter","information",JOptionPane.INFORMATION_MESSAGE);
                                    }

                                }
                            } else {
                                //pc w data show
                                System.out.println("HANI");
                                if (dis == 1) {
                                    System.out.println("if (dis == 1) ");
                                    st.executeUpdate("update salle set salle.dispo= 0 WHERE salle.numsalle=" + ns);

                                    rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                    while (rs1.next()) {
                                        System.out.println(" while (rs1.next()");
                                        iddr = rs1.getInt(1) + 1;
                                    }
                                    int mat = 0;
                                    if (Integer.parseInt(nd) > td || Integer.parseInt(np) > tp) {
                                        
                                        System.out.println("HABSOU");
                                        JOptionPane.showMessageDialog(null, "Demande Réfusé 3","ERROR",JOptionPane.ERROR_MESSAGE);
                                    } else {
                                        System.out.println(" int idmat = 0;");
                                        int idmat = 0;
                                        st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd1 + "' , '" + df1 + "' ," + mot + "," + ns + " , " + iddem + "," + i + "," + mat + ")");
                                        rs1 = st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1 and dispo=1");
                                        while (rs1.next()) {
                                            idmat = rs1.getInt(1);
                                        }
                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                        }
                                        System.out.println("1");
                                        st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd2 + "' , '" + df2 + "' ," + mot + "," + null + " , " + iddem + "," + i + "," + idmat + ")");
                                        System.out.println("11");
                                        st.executeUpdate("update materiel set dispo = 0 where idmateriel=" + idmat);
                                        System.out.println("12");
                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                        }
                                        System.out.println("iddr"+iddr);
                                        System.out.println("dd1"+dd1);
                                        System.out.println("df1"+df1);
                                        System.out.println("mot"+mot);
                                        System.out.println("ns"+ns);
                                        System.out.println("iddem"+iddem);
                                        System.out.println("i"+i);
                                        System.out.println("mat"+mat);
                                        System.out.println("13");
                                        rs1 = st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2 and dispo=1");
                                        while (rs1.next()) {
                                            idmat = rs1.getInt(1);
                                            System.out.println("2");
                                        }
                                       
                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                            System.out.println("3");
                                        }
                                        System.out.println("4");
                                        st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd2 + "' , '" + df2 + "' ," + mot + "," + null + " , " + iddem + "," + i + "," + idmat + ")");
                                        
                                        st.executeUpdate("update materiel set dispo = 0 where idmateriel=" + idmat);

                                        System.out.println("ACCEPTED 4");
                                        JOptionPane.showMessageDialog(null, "Demande Traiter","information",JOptionPane.INFORMATION_MESSAGE);

                                    }

                                }

                            }

                        } else {
                            if(!(nd.equals("0"))){
                                rs2 = st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2");
                            while (rs2.next()) {
                                td = Integer.parseInt(rs2.getString(1));
                            } 
                            
                            if (Integer.parseInt(nd) > td) {
                                    System.out.println("data22");
                                    //Réfuser
                                    JOptionPane.showMessageDialog(null, "Demande Réfusé 4","ERROR",JOptionPane.ERROR_MESSAGE);
                                } else {
                                    if (dis == 1) {
                                        //reservilou

                                        st.executeUpdate("update salle set salle.dispo= 0 WHERE salle.numsalle=" + ns);

                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                        }
                                        int mat = 0;
                                        st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd1 + "' , '" + df1 + "' ," + mot + "," + ns + " , " + iddem + "," + i + "," + mat + ")");
                                        System.out.println("ACCEPTED2222222" + iddr);
                                        System.out.println("pc332222222");
                                        //dirlou reserv
                                        int idmat = 0;
                                        rs1 = st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2 and dispo=1");
                                        while (rs1.next()) {
                                            idmat = rs1.getInt(1);
                                        }
                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                        }
                                        st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd2 + "' , '" + df2 + "' ," + mot + "," + null + " , " + iddem + "," + i + "," + idmat + ")");
                                        st.executeUpdate("update materiel set dispo = 0 where idmateriel=" + idmat);

                                        System.out.println("ACCEPTED 32222222");
                                        JOptionPane.showMessageDialog(null, "Demande Traiter","information",JOptionPane.INFORMATION_MESSAGE);
                                    }
                            
                            
                            
                            
                            }
                            
                            
                            }
                        
                        }
                        //yji hna 
                        /*
                        if(!(nd.equlas(0)){
                        if(np.equals(0)){
                        }
                        }
                        
                        
                        **/
                                    

                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                    }

                } else {

                    System.out.println("{if(!(dd2.equals(null)))");
                    int tp = 0, td = 0, iddr = 0;
                    rs1 = st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1");
                    while (rs1.next()) {
                        tp = Integer.parseInt(rs1.getString(1));
                    }
                    rs2 = st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2");
                    while (rs2.next()) {
                        td = Integer.parseInt(rs2.getString(1));
                    }

                    if (!(dd2.equals("1111-11-11"))) {

                        //reservation materiel
                        //PC
                        //DATASHOW
                        if (!(np.equals("0"))) {
                            System.out.println("pc1");
                            //le cas insersion pc 
                            if (nd.equals("0")) {
                                if (Integer.parseInt(np) > tp) {
                                    System.out.println("pc2");
                                    //Réfuser
                                    JOptionPane.showMessageDialog(null, "Demande Réfusé5","ERROR",JOptionPane.ERROR_MESSAGE);
                                } else {
                                    System.out.println("pc3");
                                    //dirlou reserv
                                    int idmat = 0;// mot = 1;
                                    rs1 = st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1 and dispo=1");
                                    while (rs1.next()) {
                                        idmat = rs1.getInt(1);
                                    }
                                    rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                    while (rs1.next()) {
                                        iddr = rs1.getInt(1) + 1;
                                    }
                                    st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd2 + "' , '" + df2 + "' ," + mot + "," + null + " , " + iddem + "," + i + "," + idmat + ")");
                                    st.executeUpdate("update materiel set dispo = 0 where idmateriel=" + idmat);

                                    System.out.println("ACCEPTED 8");
                                    JOptionPane.showMessageDialog(null, "Demande Traiter","information",JOptionPane.INFORMATION_MESSAGE);
                                }
                            } else 
                            {
                                //plasto mea hada code 
                            int mat = 0;//mot=1;
                                    if (Integer.parseInt(nd) > td || Integer.parseInt(np) > tp) {
                                        
                                       JOptionPane.showMessageDialog(null, "Demande Réfusé 6","information",JOptionPane.ERROR_MESSAGE);
                                    } else {
                                        System.out.println(" int idmat = 0;");
                                        int idmat = 0;
                                        rs1 = st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1 and dispo=1");
                                        while (rs1.next()) {
                                            idmat = rs1.getInt(1);
                                        }
                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                        }
                                        System.out.println("1");
                                        st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd2 + "' , '" + df2 + "' ," + mot + "," + null + " , " + iddem + "," + i + "," + idmat + ")");
                                        System.out.println("11");
                                        st.executeUpdate("update materiel set dispo = 0 where idmateriel=" + idmat);
                                        System.out.println("12");
                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                        }
                                        System.out.println("iddr"+iddr);
                                        System.out.println("dd1"+dd1);
                                        System.out.println("df1"+df1);
                                        System.out.println("mot"+mot);
                                        System.out.println("ns"+ns);
                                        System.out.println("iddem"+iddem);
                                        System.out.println("i"+i);
                                        System.out.println("mat"+mat);
                                        System.out.println("13");
                                        rs1 = st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2 and dispo=1");
                                        while (rs1.next()) {
                                            idmat = rs1.getInt(1);
                                            System.out.println("2");
                                        }
                                       
                                        rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                        while (rs1.next()) {
                                            iddr = rs1.getInt(1) + 1;
                                            System.out.println("3");
                                        }
                                        System.out.println("4");
                                       st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd2 + "' , '" + df2 + "' ," + mot + "," + null + " , " + iddem + "," + i + "," + idmat + ")");
                                        
                                        st.executeUpdate("update materiel set dispo = 0 where idmateriel=" + idmat);

                                        System.out.println("ACCEPTED 9");
                                        JOptionPane.showMessageDialog(null, "Demande Traiter","information",JOptionPane.INFORMATION_MESSAGE);

                                    }
                            
                            }

                        } else {
                            if ((np.equals("0"))) {

                                if (!(nd.equals("0"))) {
                                    System.out.println("datashou1");
                                    if (np.equals("0")) {
                                        if (Integer.parseInt(nd) > td) {
                                            System.out.println("datashou2");
                                            //Réfuser
                                            JOptionPane.showMessageDialog(null, "Demande Réfusé","ERROR",JOptionPane.ERROR_MESSAGE);
                                        } else {
                                            //dirlou reserv
                                            System.out.println("daatshou3");
                                            int idmat = 0; //mot = 1;
                                            rs1 = st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2 and dispo=1");
                                            while (rs1.next()) {
                                                idmat = rs1.getInt(1);
                                            }
                                            rs1 = st.executeQuery("select Max(idreservation) from reservation");
                                            while (rs1.next()) {
                                                iddr = rs1.getInt(1) + 1;
                                            }
                                            st.executeUpdate("  insert into reservation VALUES (" + iddr + ", '" + dd2 + "' , '" + df2 + "' ," + mot + "," + null + " , " + iddem + "," + i + "," + idmat + ")");
                                            st.executeUpdate("update materiel set dispo = 0 where idmateriel=" + idmat);
                                            System.out.println("ACCEPTED  10" + iddr);
                                            JOptionPane.showMessageDialog(null, "Demande Traiter","information",JOptionPane.INFORMATION_MESSAGE);

                                        }
                                    }
                                }
                            }

                        }

                    }
                }
                // donc henaya yeji ? jabli rei l fou9 nasiima 
                
                
                
                
                
            }
        } catch (Exception e) {
            
        }

        //hna salle w materiel
        /* if(!(dd1.equals(null))){
                if(!(dd2.equals(null))){
                
                    String dis="";
                rs1=st.executeQuery("SELECT dispo FROM salle where salle.numsalle="+ns);
                while(rs1.next()){ 
             dis=rs1.getString(1);
                }
            
                    if(Integer.parseInt(dis)==1){
                         int tp=0,td=0;
                         int idmat=0,mot=1,iddr=0;
            //reservation materiel
            //PC
            rs1=st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1");
            while(rs1.next()){ tp = Integer.parseInt(rs1.getString(1));
}
            //DATASHOW
            rs2=st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2");
            while(rs2.next()){ td=Integer.parseInt(rs2.getString(1));}
            if(!(np.equals(null)) ){
                if(nd.equals(null)){
                if(Integer.parseInt(np)>tp){
                    System.out.println("REFUSED1");
                }
                else {
                    //dirlou reserv
                     
                    rs1=st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1 and dispo=1");
                    while(rs1.next()){
                    idmat=rs1.getInt(1);
                    }
                     rs1=st.executeQuery("select Max(idreservation) from reservation");
                    while(rs1.next()){
                          iddr = rs1.getInt(1)+1;
                    }
                    st.executeUpdate("  insert into reservation VALUES ("+iddr+", '"+dd2+"' , '"+df2+"' ,"+mot+","+ns+" , "+iddem+","+i+","+idmat+")");
                    st.executeUpdate("update materiel set dispo = 0 where idmateriel="+idmat);
                    
                System.out.println("ACCEPTED1 "+iddr);
                    System.out.println("ACCEPTED2");
                }
            
            }}
            if(!(nd.equals(null))){
                 if(np.equals(null)){
                   if(Integer.parseInt(nd)>td){
                       System.out.println("REFUSED2");
                }
                else {
                    //dirlou reserv
                    
                    rs1=st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2 and dispo=1");
                    while(rs1.next()){
                    idmat=rs1.getInt(1);
                    }
                     rs1=st.executeQuery("select Max(idreservation) from reservation");
                    while(rs1.next()){
                    iddr=rs1.getInt(1)+1;
                    }
                    st.executeUpdate("  insert into reservation VALUES ("+iddr+", '"+dd2+"' , '"+df2+"' ,"+mot+","+ns+" , "+iddem+","+i+","+idmat+")");
                    st.executeUpdate("update materiel set dispo = 0 where idmateriel="+idmat);
                    
                System.out.println("ACCEPTED3 "+iddr);
                    System.out.println("ACCEPTED3");
                } 
            }   
              }
            if(!(np.equals(null)) && !(nd.equals(null))){
                   if(Integer.parseInt(nd)>td || Integer.parseInt(np)>tp){
                       System.out.println("REFUSED3");
                }
                else {
                    //dirlou reserv
                    
                    rs1=st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1 and dispo=1");
                    while(rs1.next()){
                    idmat=rs1.getInt(1);
                    }
                     rs1=st.executeQuery("select Max(idreservation) from reservation");
                    while(rs1.next()){
                    iddr=rs1.getInt(1)+1;
                    }
                    st.executeUpdate("  insert into reservation VALUES ("+iddr+", '"+dd2+"' , '"+df2+"' ,"+mot+","+ns+" , "+iddem+","+i+","+idmat+")");
                    st.executeUpdate("update materiel set dispo = 0 where idmateriel="+idmat);
                       
                   
               
                    rs1=st.executeQuery("SELECT MAX(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2 and dispo=1");
                    while(rs1.next()){
                    idmat=rs1.getInt(1);
                    }
                     rs1=st.executeQuery("select Max(idreservation) from reservation");
                    while(rs1.next()){
                    iddr=rs1.getInt(1)+1;
                    }
                    st.executeUpdate("  insert into reservation VALUES ("+iddr+", '"+dd2+"' , '"+df2+"' ,"+mot+","+ns+" , "+iddem+","+i+","+idmat+")");
                    st.executeUpdate("update materiel set dispo = 0 where idmateriel="+idmat);
                    iddr+=1;
                    int idmm=0;
                    
                st.executeUpdate("  insert into reservation VALUES ("+iddr+", '"+dd1+"' , '"+df1+"' ,"+mot+","+ns+" , "+iddem+","+i+","+idmm+")");
                   st.executeUpdate("update salle set dispo = 0 where numsalle="+ns);
                    
                
                    
                   System.out.println("ACCEPTED4");
                } 
              }
                    }
                
                    else {System.out.println("REEEEEEFUUUUUUUUUUSE");}
                
                }
            
            
            
            
            
            }
            
        }
           
        }catch (Exception e){}
      //ou je fais mes TESTS  
      /*  try{
           int i=Integer.parseInt(tf.getText());
            String ns="",nd="",np="";
            int tp=0,td=0;
            
            rs=st.executeQuery("select * from demande where demande.iddem="+i);
             np=t3.getText();
            nd=t2.getText();
            
            rs1=st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=1");
            while(rs1.next()){  tp = Integer.parseInt(rs1.getString(1));}
           rs2=st.executeQuery("SELECT COUNT(materiel.idmateriel) FROM materiel WHERE materiel.idtypemateriel=2");
            while(rs2.next()){  td=Integer.parseInt(rs2.getString(1));}
                
           if(!(np.equals(null)) ){
                 
                if(Integer.parseInt(np)>tp){
                //Réfuser
                    System.out.println("REFUSED");
                }
                else {
                    System.out.println("ACCEPTED");
                }
                 
                }
           int npp=0,ndd=0;
          // if(np.equals("null")){ System.out.println("tu travaille avec null");}
          // else { npp=Integer.parseInt(np);}
          // if(nd.equals("null")){ System.out.println("tu travaille avec null");}
          // else { ndd=Integer.parseInt(nd);}
           
           
           if(!(np.equals(""))){
               npp=Integer.parseInt(np);
               if(nd.equals("null")){
                   if(npp>tp){
                       System.out.println("Refused");
                   }
                   else {
                       System.out.println("ACCEPTED");
                   }
               }*/
        //}
        //}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        LOGIN s=new LOGIN();
        this.dispose();
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        WindowEvent wc=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wc);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        MENU m;        // TODO add your handling code here:
        m = new MENU(this.n,this.p,this.tt);
        this.dispose();
        m.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gererreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gererreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gererreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gererreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gererreservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea t;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JLabel tf;
    // End of variables declaration//GEN-END:variables
}
