/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sia;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Winsido
 */
public class INSCRIPTION extends javax.swing.JFrame {
    SeConnecter c=new SeConnecter();

ResultSet rs,rs1,rs2;
Statement st;


    /**
     * Creates new form INSCRIPTION
     */
    public INSCRIPTION() {
        initComponents();
         this.setSize(1097, 640);
        
           try {
            st=c.obtenirCon().createStatement();
            rs=st.executeQuery("select* from individu");
              
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur Séléction","Erreur",JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        n2 = new javax.swing.JTextField();
        n1 = new javax.swing.JTextField();
        p2 = new javax.swing.JPasswordField();
        p1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        e2 = new javax.swing.JRadioButton();
        e1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        e3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        n3 = new javax.swing.JTextField();
        e4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 94, 166));
        jPanel3.setLayout(null);
        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 190, 610);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/edubase.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(430, 10, 380, 147);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("MOT DE PASSE :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(210, 320, 140, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Confirmer Mot de passe :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(550, 320, 210, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("je suis un : ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(210, 440, 110, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("user : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(820, 210, 110, 50);

        n2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(n2);
        n2.setBounds(570, 260, 200, 40);

        n1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(n1);
        n1.setBounds(220, 260, 200, 40);
        jPanel2.add(p2);
        p2.setBounds(550, 370, 190, 50);
        jPanel2.add(p1);
        p1.setBounds(220, 370, 190, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setText("NOM :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(210, 210, 80, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel7.setText("NOM :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(210, 210, 80, 50);

        e2.setText("Enseignant");
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        jPanel2.add(e2);
        e2.setBounds(450, 450, 99, 25);

        e1.setText("Etudiant");
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        jPanel2.add(e1);
        e1.setBounds(330, 450, 75, 25);

        jButton1.setBackground(new java.awt.Color(0, 94, 166));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VALIDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(820, 520, 140, 50);

        e3.setText("Secretaire");
        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });
        jPanel2.add(e3);
        e3.setBounds(720, 450, 87, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setText("PRENOM :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(560, 210, 110, 50);

        n3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(n3);
        n3.setBounds(830, 260, 200, 40);

        e4.setText("Gestionnaire");
        e4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4ActionPerformed(evt);
            }
        });
        jPanel2.add(e4);
        e4.setBounds(590, 450, 99, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1140, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
if(e1.isSelected()==true){
e2.setSelected(false);
e3.setSelected(false);
e4.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
if(e2.isSelected()){
e1.setSelected(false);
e4.setSelected(false);
e3.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_e2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String user=n3.getText();
            int max=0;
            String nom="",prenom="";
            String n=n1.getText().toUpperCase();
            String p=n2.getText().toUpperCase();
            String pass1=p1.getText().toString();
            String pass2=p2.getText().toString();
            rs=st.executeQuery("select * from individu where nomind='"+n+"' and prenomind='"+p+"'");
            while(rs.next()){
            nom=rs.getString(2);
            prenom=rs.getString(3);
            }
            if(n.equals(nom) && p.equals(prenom)){
                JOptionPane.showMessageDialog(null, "Vous etes déja inscrit","Erreur",JOptionPane.ERROR_MESSAGE);
                
            }
            else {
               if(e1.isSelected()){
                   int x=1;
                   
                   if(pass1.equals(pass2)){
                       System.out.println("Im here");
                   rs=st.executeQuery("select max(idindividu) from individu");
                   
                   while(rs.next()){
                   max=rs.getInt(1)+1;
                   }
                     System.out.println("Im here");  
                   st.executeUpdate("insert into individu VALUES("+max+" , '"+n+"' , '"+p+"' , "+x+" , '"+pass1+"', '"+user+"')");
                   JOptionPane.showMessageDialog(null, "INSCRIPTION VALIDE","INFO",JOptionPane.INFORMATION_MESSAGE);
                   MENU m=new MENU(n, p, max);
                   this.dispose();
                   m.setVisible(true);
                   }
                   else {
                   JOptionPane.showMessageDialog(null, "Vérifié votre mot de passe","Erreur",JOptionPane.ERROR_MESSAGE);
                   }
               }
                if(e2.isSelected()){
                   if(pass1.equals(pass2)){
                   //hna insertion enseignant
                   int x=2;
                   
                   if(pass1.equals(pass2)){
                       System.out.println("Im here");
                   rs=st.executeQuery("select max(idindividu) from individu");
                   
                   while(rs.next()){
                   max=rs.getInt(1)+1;
                   }
                     System.out.println("Im here");  
                   st.executeUpdate("insert into individu VALUES("+max+" , '"+n+"' , '"+p+"' , "+x+" , '"+pass1+"', '"+user+"')");
                   JOptionPane.showMessageDialog(null, "INSCRIPTION VALIDE","INFO",JOptionPane.INFORMATION_MESSAGE);
                   MENU m=new MENU(n, p, max);
                   this.dispose();
                   m.setVisible(true);
                   }
                   else {
                   JOptionPane.showMessageDialog(null, "Vérifié votre mot de passe","Erreur",JOptionPane.ERROR_MESSAGE);
                   }
                   }
                   else {
                   JOptionPane.showMessageDialog(null, "Vérifié votre mot de passe","Erreur",JOptionPane.ERROR_MESSAGE);
                   }
               }
                if(e3.isSelected()){
                   int x=3;
                   
                   if(pass1.equals(pass2)){
                       System.out.println("Im here");
                   rs=st.executeQuery("select max(idindividu) from individu");
                   
                   while(rs.next()){
                   max=rs.getInt(1)+1;
                   }
                     System.out.println("Im here");  
                   st.executeUpdate("insert into individu VALUES("+max+" , '"+n+"' , '"+p+"' , "+x+" , '"+pass1+"', '"+user+"')");
                   JOptionPane.showMessageDialog(null, "INSCRIPTION VALIDE","INFO",JOptionPane.INFORMATION_MESSAGE);
                   MENU m=new MENU(n, p, max);
                   this.dispose();
                   m.setVisible(true);
                   }
                   else {
                   JOptionPane.showMessageDialog(null, "Vérifié votre mot de passe","Erreur",JOptionPane.ERROR_MESSAGE);
                   }
               }
                if(e4.isSelected()){
                   if(pass1.equals(pass2)){
                   //hna insertion enseignant
                   int x=4;
                   
                   if(pass1.equals(pass2)){
                       System.out.println("Im here");
                   rs=st.executeQuery("select max(idindividu) from individu");
                   
                   while(rs.next()){
                   max=rs.getInt(1)+1;
                   }
                     System.out.println("Im here");  
                   st.executeUpdate("insert into individu VALUES("+max+" , '"+n+"' , '"+p+"' , "+x+" , '"+pass1+"', '"+user+"')");
                   JOptionPane.showMessageDialog(null, "INSCRIPTION VALIDE","INFO",JOptionPane.INFORMATION_MESSAGE);
                   MENU m=new MENU(n, p, max);
                   this.dispose();
                   m.setVisible(true);
                   }
                   else {
                   JOptionPane.showMessageDialog(null, "Vérifié votre mot de passe","Erreur",JOptionPane.ERROR_MESSAGE);
                   }
                   }
                   else {
                   JOptionPane.showMessageDialog(null, "Vérifié votre mot de passe","Erreur",JOptionPane.ERROR_MESSAGE);
                   }
               }
                
                
                
            }
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
if(e3.isSelected()){
e2.setSelected(false);
e1.setSelected(false);
e4.setSelected(false);}
    }//GEN-LAST:event_e3ActionPerformed

    private void e4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4ActionPerformed
if(e4.isSelected()){
e2.setSelected(false);
e1.setSelected(false);
e3.setSelected(false);}
             // TODO add your handling code here:
    }//GEN-LAST:event_e4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INSCRIPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INSCRIPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INSCRIPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INSCRIPTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INSCRIPTION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton e1;
    private javax.swing.JRadioButton e2;
    private javax.swing.JRadioButton e3;
    private javax.swing.JRadioButton e4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    // End of variables declaration//GEN-END:variables
}
