/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor. */
package sia;


import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Winsido
 */
public class LOGIN extends javax.swing.JFrame {
     SeConnecter c=new SeConnecter();

ResultSet rs,rs1,rs2;
Statement st;

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents();
        this.setSize(504, 581);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        try {
            st=c.obtenirCon().createStatement();
            rs=st.executeQuery("select* from individu");
              
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur Séléction","Erreur",JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        t2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(225, 231, 235));
        t1.setText("Entrer votre user name");
        t1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 94, 166), null));
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t1MousePressed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(90, 170, 320, 50);

        b1.setBackground(new java.awt.Color(0, 94, 166));
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("Connexion");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                b1MousePressed(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(90, 360, 320, 50);

        t2.setText("SEYYYYIIIIskdlsddsjdfn");
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                t2MouseReleased(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(90, 260, 320, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/edubase.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 40, 330, 80);

        jLabel2.setForeground(new java.awt.Color(0, 94, 166));
        jLabel2.setText("voulez-vous s'inscrire ? ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 320, 250, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MousePressed
t1.setText("");
t1.setForeground(Color.black);

    }//GEN-LAST:event_t1MousePressed

    private void t2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseReleased
t2.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_t2MouseReleased

    private void b1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MousePressed
        // TODO add your handling code here:
        String user=t1.getText();
        String pass=t2.getText();
    }//GEN-LAST:event_b1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
INSCRIPTION n=new INSCRIPTION();
this.dispose();
n.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        try {
            String user="",pass="",nom="",prenom="";
            int t=0;
            String u=t1.getText();
            String p=t2.getText().toString();
            System.out.println("chakib");
            rs=st.executeQuery("select user , pass, nomind , prenomind , idtypeindividu  from individu  where user='"+u+"'");
            while(rs.next()){
            user=rs.getString(1);
            pass=rs.getString(2);
            nom=rs.getString(3);
            prenom=rs.getString(4);
            t=rs.getInt(5);
            
            }
            
            if(u.equals(user)){
                if(p.equals(pass)){
                    JOptionPane.showMessageDialog(null, "Bonjour "+nom+" "+prenom,"INFO",JOptionPane.INFORMATION_MESSAGE);
                MENU m=new MENU(nom,prenom,t);
                this.dispose();
                m.setVisible(true);
                }
                else {
                 JOptionPane.showMessageDialog(null, "Vérifie votre mot de passe ","ERREUR",JOptionPane.ERROR_MESSAGE);
                }
            }
            else {
            JOptionPane.showMessageDialog(null, "ce compte n'existe pas  ","ERREUR",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables
}
