/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sia;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Winsido
 */
public class MENU extends javax.swing.JFrame {
    SeConnecter c=new SeConnecter();

ResultSet rs,rs1,rs2;
Statement st;

    /**
     * Creates new form MENU
     */
String n,p;
int t;
    public MENU(String n,String p,int t) {
        initComponents();
        this.setSize(842,596);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
       this.n=n;
       this.p=p;
       this.t=t;
       
        if(this.t==1 || this.t==2){
       gr.setEnabled(false);
        gm.setEnabled(false);
        am.setEnabled(false);
        mm.setEnabled(false);
        sm.setEnabled(false);
        gs.setEnabled(false);
        as.setEnabled(false);
        ms.setEnabled(false);
        ss.setEnabled(false);
        r.setVisible(false);
        s.setVisible(false);
        m.setVisible(false);
        }
        if(this.t==4){
        gr.setEnabled(false);
        r.setVisible(false);
        }
    }

    MENU() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Deci = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        ahhahahha7 = new javax.swing.JMenu();
        gr = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        gm = new javax.swing.JMenuItem();
        am = new javax.swing.JMenuItem();
        mm = new javax.swing.JMenuItem();
        sm = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        gs = new javax.swing.JMenuItem();
        as = new javax.swing.JMenuItem();
        ms = new javax.swing.JMenuItem();
        ss = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/edubase.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 0, 510, 150);

        r.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/r.png"))); // NOI18N
        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rMouseClicked(evt);
            }
        });
        jPanel1.add(r);
        r.setBounds(570, 340, 250, 180);

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/d.png"))); // NOI18N
        d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dMouseClicked(evt);
            }
        });
        jPanel1.add(d);
        d.setBounds(280, 140, 250, 180);

        m.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/m.png"))); // NOI18N
        m.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMouseClicked(evt);
            }
        });
        jPanel1.add(m);
        m.setBounds(10, 350, 250, 180);

        s.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/s.png"))); // NOI18N
        s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sMouseClicked(evt);
            }
        });
        jPanel1.add(s);
        s.setBounds(290, 340, 250, 180);

        jMenu1.setText("LOG OUT");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Deci.setText("Déconnexion");
        Deci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeciActionPerformed(evt);
            }
        });
        jMenu1.add(Deci);

        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        ahhahahha7.setText("Nouveau");
        ahhahahha7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahhahahha7ActionPerformed(evt);
            }
        });

        gr.setText("Gerer reservation ");
        gr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grActionPerformed(evt);
            }
        });
        ahhahahha7.add(gr);
        ahhahahha7.add(jSeparator4);

        gm.setText("Gerer materiel");
        gm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmActionPerformed(evt);
            }
        });
        ahhahahha7.add(gm);

        am.setText("Ajouter materiel");
        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });
        ahhahahha7.add(am);

        mm.setText("Modifier materiel");
        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });
        ahhahahha7.add(mm);

        sm.setText("Supprimer materiel");
        sm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smActionPerformed(evt);
            }
        });
        ahhahahha7.add(sm);
        ahhahahha7.add(jSeparator2);

        gs.setText("Gerer salle");
        gs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsActionPerformed(evt);
            }
        });
        ahhahahha7.add(gs);

        as.setText("Ajouter salle");
        as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asActionPerformed(evt);
            }
        });
        ahhahahha7.add(as);

        ms.setText("Modifier salle");
        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });
        ahhahahha7.add(ms);

        ss.setText("Supprimer salle");
        ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssActionPerformed(evt);
            }
        });
        ahhahahha7.add(ss);
        ahhahahha7.add(jSeparator3);

        jMenuItem10.setText("Faire une demande ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        ahhahahha7.add(jMenuItem10);

        jMenuBar1.add(ahhahahha7);

        jMenu3.setText("Réglages");

        jMenuItem12.setText("Modifier les informations personnelles ");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Changer le mot de passe");
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeciActionPerformed
LOGIN s=new LOGIN(); 
this.dispose();
s.setVisible(true);
    }//GEN-LAST:event_DeciActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
WindowEvent wc=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);    
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wc);   
       // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void gmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmActionPerformed
gerermateriel gm=new gerermateriel(this.n,this.p,this.t);
        this.dispose();
        gm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_gmActionPerformed

    private void ahhahahha7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahhahahha7ActionPerformed
        
    }//GEN-LAST:event_ahhahahha7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
gererdemande gd=new gererdemande(this.n,this.p,this.t);
        this.dispose();
        gd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void grActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grActionPerformed
gererreservation gr=new gererreservation(this.n,this.p,this.t);
        this.dispose();
        gr.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_grActionPerformed

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
ajoutermateriel am=new ajoutermateriel(this.n,this.p,this.t);
this.dispose();
am.setVisible(true);
    }//GEN-LAST:event_amActionPerformed

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
modifiermateriel mm= new modifiermateriel("", "",this.n,this.p,this.t);
this.dispose();
mm.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_mmActionPerformed

    private void smActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smActionPerformed
supprimermateriell sm=new supprimermateriell(this.n,this.p,this.t);
this.dispose();
sm.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_smActionPerformed

    private void gsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsActionPerformed
gerer gs=new gerer(this.n,this.p,this.t);
this.dispose();
gs.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_gsActionPerformed

    private void asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asActionPerformed
ajoutersalle as=new ajoutersalle(this.n, this.p,this.t);
this.dispose();
as.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_asActionPerformed

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
gerer g=new gerer(this.n, this.p,this.t);
this.dispose();
g.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_msActionPerformed

    private void ssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssActionPerformed
supprimersalle ss=new supprimersalle(this.n, this.p,this.t);
this.dispose();
ss.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ssActionPerformed

    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
 gererdemande d = new gererdemande(this.n,this.p, this.t);
 this.dispose();
d.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_dMouseClicked

    private void mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMouseClicked
gerermateriel d = new gerermateriel(this.n,this.p, this.t);
 this.dispose();
d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_mMouseClicked

    private void sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseClicked
gerer d = new gerer(this.n,this.p, this.t);
 this.dispose();
d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_sMouseClicked

    private void rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseClicked
gererreservation d = new gererreservation(this.n,this.p, this.t);
 this.dispose();
d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_rMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Deci;
    private javax.swing.JMenu ahhahahha7;
    private javax.swing.JMenuItem am;
    private javax.swing.JMenuItem as;
    private javax.swing.JLabel d;
    private javax.swing.JMenuItem gm;
    private javax.swing.JMenuItem gr;
    private javax.swing.JMenuItem gs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel m;
    private javax.swing.JMenuItem mm;
    private javax.swing.JMenuItem ms;
    private javax.swing.JLabel r;
    private javax.swing.JLabel s;
    private javax.swing.JMenuItem sm;
    private javax.swing.JMenuItem ss;
    // End of variables declaration//GEN-END:variables
}
