/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sia;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Winsido
 */
public class modifiermateriel extends javax.swing.JFrame {
SeConnecter c=new SeConnecter();

ResultSet rs;
Statement st;
String id,nss,dateA,dateFG,n,p;
int t;
    /**
     * Creates new form modifiermateriel
     */
    public modifiermateriel(String id,String nss,String n,String p,int t) {
        initComponents();this.setSize(523, 681);
        this.setResizable(false);
        t1.setText(""+id);
        t2.setText(""+nss);
        this.n=n;
        this.p=p;
        this.t=t;
        
        
        
     
        this.setLocationRelativeTo(null);
        try {
            st=c.obtenirCon().createStatement();
            rs=st.executeQuery("select* from materiel");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur Séléction","Erreur",JOptionPane.ERROR_MESSAGE);
        }
    }

    private modifiermateriel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        d2 = new com.toedter.calendar.JDateChooser();
        d1 = new com.toedter.calendar.JDateChooser();
        c2 = new javax.swing.JComboBox<>();
        c1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sia/edubase.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 0, 333, 131);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Endroit de stockage");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 500, 220, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("ID materiel");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 170, 190, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("nom materiel");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 230, 190, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Date D'achat");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 290, 190, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Date fin de garantie");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 360, 220, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("type de materiel");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 430, 190, 40);

        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(t2);
        t2.setBounds(270, 230, 190, 30);

        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(t1);
        t1.setBounds(270, 170, 190, 30);
        jPanel1.add(d2);
        d2.setBounds(270, 360, 190, 30);
        jPanel1.add(d1);
        d1.setBounds(270, 290, 190, 30);

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bureau d'etude", "secraitaria", "magasin", "scolarité" }));
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c2MouseExited(evt);
            }
        });
        jPanel1.add(c2);
        c2.setBounds(270, 500, 180, 30);

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pc portable", "pc fixe", "datashow" }));
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                c1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                c1MouseExited(evt);
            }
        });
        jPanel1.add(c1);
        c1.setBounds(270, 430, 180, 30);

        jButton1.setBackground(new java.awt.Color(0, 94, 166));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 570, 120, 40);

        jMenu1.setText("Log out");

        jMenuItem1.setText("Déconnexion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Quitté");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("page Menu");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Page Precedent");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseEntered
c1.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_c1MouseEntered

    private void c2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseEntered
c2.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_c2MouseEntered

    private void c1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseExited
c1.hidePopup();        // TODO add your handling code here:
    }//GEN-LAST:event_c1MouseExited

    private void c2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseExited
c2.hidePopup();        // TODO add your handling code here:
    }//GEN-LAST:event_c2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            String x=c1.getSelectedItem().toString();
            int i=0;
            if(x.equals("pc portable")){i=1;}
            else {if(x.equals("pc fixe")) { i=2;}
                else { if(x.equals("datashow")){i=3;} }
            }
            String y=c2.getSelectedItem().toString();
            int j=0;
            //Bureau d'etude, secraitaria, magasin, scolarité
            if(y.equals("Bureau d'etude")){j=1;}
            else {if(y.equals("secraitaria")) { j=2;}
                else { if(y.equals("magasin")){j=3;}
                    else {if(y.equals("scolarité")){j=4;}}}
            }
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String datea=sdf.format(d1.getDate());
            String datef=sdf.format(d2.getDate());
            int k =Integer.parseInt(t1.getText());
//idmateriel nommateriel dateAchat dateFingarantie idtypemateriel idburea
String y1="",y2="",m1="",m2="",j1="",j2="";
                    for(int m=0;m<4;m++){
                        y1=y1+datea.charAt(m);
                        y2=y2+datef.charAt(m); }
                    for(int m=5;m<7;m++){
                        m1=m1+datea.charAt(m);
                        m2=m2+datef.charAt(m); }
                    for(int m=8;m<10;m++){
                        j1=j1+datea.charAt(m);
                        j2=j2+datef.charAt(m); }
                    
                    System.out.println(""+y1);
                    System.out.println(""+y2);
                    System.out.println(""+m1);
                    System.out.println(""+m2);
                     System.out.println(""+j1);
                    System.out.println(""+j2);
                       int yy1 = Integer.parseInt(y1);
                       int yy2 = Integer.parseInt(y2);
                       int mm1 = Integer.parseInt(m1);
                       int mm2 = Integer.parseInt(m2);
                       int jj1 = Integer.parseInt(j1);
                       int jj2 = Integer.parseInt(j2);
                      /*
                       if(yy1==yy2){
                           if(mm1==mm2){
                           if(jj1>jj2){JOptionPane.showMessageDialog(null, "Erreur : date fin de garantie doit etre suppérieur à la date d'achat de produit","Erruer",JOptionPane.ERROR_MESSAGE);}
                           else {st.executeUpdate("update materiel set nommateriel=' "+t2.getText()+"', dateAchat=' "+datea+"' ,dateFingarantie=' "+datef+"' , idtypemateriel="+i+" , idbureau= "+j+" where idmateriel= "+k);
                           JOptionPane.showMessageDialog(null, "materiel modifié","information",JOptionPane.INFORMATION_MESSAGE);}
                           
                           
                           } else { if(mm1>mm2){JOptionPane.showMessageDialog(null, "Erreur : date fin de garantie doit etre suppérieur à la date d'achat de produit","Erruer",JOptionPane.ERROR_MESSAGE);}
                           else {st.executeUpdate("update materiel set nommateriel=' "+t2.getText()+"', dateAchat=' "+datea+"' ,dateFingarantie=' "+datef+"' , idtypemateriel="+i+" , idbureau= "+j+" where idmateriel= "+k);
                           JOptionPane.showMessageDialog(null, "materiel modifié","information",JOptionPane.INFORMATION_MESSAGE);}}
                       } else {
                       if(mm1>mm2) {JOptionPane.showMessageDialog(null, "Erreur : date fin de garantie doit etre suppérieur à la date d'achat de produit","Erruer",JOptionPane.ERROR_MESSAGE);}
                       else {st.executeUpdate("update materiel set nommateriel=' "+t2.getText()+"', dateAchat=' "+datea+"' ,dateFingarantie=' "+datef+"' , idtypemateriel="+i+" , idbureau= "+j+" where idmateriel= "+k);
                           JOptionPane.showMessageDialog(null, "materiel modifié","information",JOptionPane.INFORMATION_MESSAGE);}
                       
                       
                       }*/
                      
                      
                      if(yy1>yy2){JOptionPane.showMessageDialog(null, "Erreur : date fin de garantie doit etre suppérieur à la date d'achat de produit","Erruer",JOptionPane.ERROR_MESSAGE);}
                       else {
                       if(yy1==yy2){
                           if(mm1==mm2){
                           if(jj1>jj2){JOptionPane.showMessageDialog(null, "Erreur : date fin de garantie doit etre suppérieur à la date d'achat de produit","Erruer",JOptionPane.ERROR_MESSAGE);}
                           else {st.executeUpdate("update materiel set nommateriel=' "+t2.getText()+"', dateAchat=' "+datea+"' ,dateFingarantie=' "+datef+"' , idtypemateriel="+i+" , idbureau= "+j+" where idmateriel= "+k);
                           JOptionPane.showMessageDialog(null, "materiel modifié","information",JOptionPane.INFORMATION_MESSAGE);}
                           
                           
                           
                           } else
                           { if(mm1>mm2){JOptionPane.showMessageDialog(null, "Erreur : date fin de garantie doit etre suppérieur à la date d'achat de produit","Erruer",JOptionPane.ERROR_MESSAGE);}
                           else 
                           {st.executeUpdate("update materiel set nommateriel=' "+t2.getText()+"', dateAchat=' "+datea+"' ,dateFingarantie=' "+datef+"' , idtypemateriel="+i+" , idbureau= "+j+" where idmateriel= "+k);
                           JOptionPane.showMessageDialog(null, "materiel modifié","information",JOptionPane.INFORMATION_MESSAGE);}}
                       } else {
                       if(mm1>mm2) 
                       {JOptionPane.showMessageDialog(null, "Erreur : date fin de garantie doit etre suppérieur à la date d'achat de produit","Erruer",JOptionPane.ERROR_MESSAGE);}
                       
                       
                       else {
                      st.executeUpdate("update materiel set nommateriel=' "+t2.getText()+"', dateAchat=' "+datea+"' ,dateFingarantie=' "+datef+"' , idtypemateriel="+i+" , idbureau= "+j+" where idmateriel= "+k);
                           JOptionPane.showMessageDialog(null, "materiel modifié","information",JOptionPane.INFORMATION_MESSAGE);
                       }
                       
                       
                       }
                    
                       }

   /*st.executeUpdate("update materiel set nommateriel=' "+t2.getText()+"', dateAchat=' "+datea+"' ,dateFingarantie=' "+datef+"' , idtypemateriel="+i+" , idbureau= "+j+" where idmateriel= "+k);
            JOptionPane.showMessageDialog(null, "materiel modifié","information",JOptionPane.INFORMATION_MESSAGE);*/

gerermateriel m = new gerermateriel(this.n,this.p,this.t);
this.dispose();
m.setVisible(true);        
} catch (Exception e) {JOptionPane.showMessageDialog(null, "Errfdfdeur","Erruer",JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        LOGIN s=new LOGIN();
        this.dispose();
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        WindowEvent wc=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wc);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        MENU m;        // TODO add your handling code here:
        m = new MENU(this.n,this.p,this.t);
        this.dispose();
        m.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
gerermateriel m;       // TODO add your handling code here:
        m = new gerermateriel(this.n,this.p,this.t);
        this.dispose();
        m.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
gerermateriel m;       // TODO add your handling code here:
        m = new gerermateriel(this.n,this.p,this.t);
        this.dispose();
        m.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifiermateriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifiermateriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifiermateriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifiermateriel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifiermateriel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
